#!/bin/bash
# Deploy Script for Frontend and Backend
ssh -tt ubuntu@quadcore.news 'bash -s' << 'DEPLOY'
sudo systemctl daemon-reload
sudo systemctl stop nginx
sudo systemctl stop quadcore

cd /var/www
sudo rm -rf quadcore.news

sudo git clone https://github.com/kmu-sv/quadcore-serving.git
sudo mv quadcore-serving/frontend quadcore.news
sudo mv quadcore-serving/backend quadcore.news/quadcore
sudo cp maintenance/.env quadcore.news/quadcore/.env
sudo rm -rf quadcore-serving

sudo apt-get install python3-dev python3-pip
sudo pip3 install -r quadcore.news/quadcore/requirements.txt

sudo systemctl daemon-reload
sudo systemctl start nginx
sudo systemctl start quadcore
sudo chmod 755 quadcore.news

exit
DEPLOY